# Generated by Django 4.1.2 on 2022-10-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='baby_food_name',
            field=models.CharField(default='', max_length=50, verbose_name='Название детского питания'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='composition',
            field=models.CharField(default='', max_length=150, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_available',
            field=models.BooleanField(default='1', verbose_name='Доступен ли товар?'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='Цена'),
        ),
    ]
